{{- define "k8s-as-helm-lib.job.tpl" -}}
spec:
{{ if .Values.ttlSecondsAfterFinished }}
  ttlSecondsAfterFinished: {{ .Values.ttlSecondsAfterFinished }}
{{- end }}
{{ if .Values.backoff }}
  backoffLimit: {{ .Values.backoff }} 
{{- end }}
{{ if .Values.deadlineSec }}
  activeDeadlineSeconds: {{ .Values.deadlineSec }}
{{- end }}
{{ if .Values.parallelism }}
  parallelism:  {{ .Values.parallelism }}
{{- end }}
{{ if .Values.completions }}
  completions:  {{ .Values.completions }}
{{- end }}
{{ if .Values.completionMode }}
  completionMode: {{ .Values.completionMode }}
{{- end }}
  template:
    metadata:
{{- if .Values.podAnnotations }}
      annotations:
{{ toYaml .Values.podAnnotations | indent 8}}
{{- end }}
{{- if .Values.podLabels }}
      labels:
{{ toYaml .Values.podLabels | indent 8}}
{{- end }}
{{ tpl ( include "k8s-as-helm-lib.pod.tpl" . ) . | indent 4 }}
{{- end -}}
