kind: NetworkPolicy
apiVersion: {{ template "apiVersion" . }}
metadata:
  name: {{ template "networkpolicy.name" . }}
{{- if .Values.annotations }}
  annotations:
{{ toYaml .Values.annotations | indent 4}}
{{- end }}
  labels:
    app: {{ template "networkpolicy.name" . }}
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.labels }}
{{ toYaml .Values.labels | indent 4 }}
{{- end }}
spec:
{{- if .Values.podSelector }}
  podSelector:
    matchLabels:
{{ toYaml .Values.podSelector.matchLabels | indent 7 }}
{{- end }}
{{- if or .Values.ingress .Values.egress }}
  policyTypes:
{{- if .Values.ingress }}
    - Ingress
{{- end }}
{{- if .Values.egress }}
    - Egress
{{- end }}
{{- end }}
{{- if .Values.egress }}
  egress:
{{-  range $egressPort := .Values.egressPorts }}
    - ports:           
{{ toYaml $egressPort | indent 9 }}
{{- end }}
{{- end }}
{{- if .Values.ingress }}
  ingress:
{{-  range $ingressPort := .Values.ingressPorts }}
    - ports:           
{{ toYaml $ingressPort | indent 9 }}
{{- end }}
{{- end }}

