apiVersion: {{ template "apiVersion" . }}
kind: ServiceAccount
metadata:
{{- if .Values.annotations }}
  annotations:
{{ toYaml .Values.annotations | indent 4}}
{{- end }}
  labels:
    app: {{ template "serviceaccount.name" . }}
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.labels }}
{{ toYaml .Values.labels | indent 4 }}
{{- end }}
  name: {{ template "serviceaccount.name" . }}
automountServiceAccountToken: {{ .Values.automountToken }}
{{- with .Values.imagePullSecrets}}
imagePullSecrets:
{{- range $name := . }}
  - name: {{ $name }}
{{- end }}
{{- end }}
