apiVersion: v2
appVersion: "v1.0.0"
home: https://github.com/ameijer/k8s-as-helm
description: Helm Chart represeting a single PDB Kubernetes API object
name: pdb
version: 1.0.0
maintainers:
  - name: ameijer
    url: https://github.com/ameijer
keywords:
- pdb
- api
- primitives
- disruption
- poddisruptionbudget
- budget
- pod
