apiVersion: {{ template "apiVersion" . }}
kind: PodDisruptionBudget
metadata:
  name:  {{ template "pdb.name" . }}-pdb
  labels:
      app: {{ template "pdb.name" . }}
      chart: {{ .Chart.Name }}
      release: {{ .Release.Name }}
      heritage: {{ .Release.Service }}
spec:
  minAvailable: {{ .Values.minAvailable }}
  maxUnvailable: {{ .Values.maxUnavailable }}
  selector:
    matchLabels:
{{ if .Values.selector }}
      {{ toYaml .Values.selector.matchLabels | indent 7 }}
{{ end }}
