kind: Pod
apiVersion: {{ template "apiVersion" . }}
metadata:
  name: {{ template "pod.name" . }}
{{- if .Values.annotations }}
  annotations:
{{ toYaml .Values.annotations | indent 4}}
{{- end }}
  labels:
    app: {{ template "pod.name" . }}
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.labels }}
{{ toYaml .Values.labels | indent 4 }}
{{- end }}
{{ tpl ( include "k8s-as-helm-lib.pod.tpl" . ) . }}
